service: serverless-aws-lambda

provider:
  name: aws
  runtime: nodejs12.x

functions:
  helloworld:
    handler: handler.run
    events:
      - http:
          path: /
          method: get

resources:
  Resources:
    TodosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: todos
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
